--Legends

INSERT INTO legend(id, name, img_url) VALUES(default, 'Bloodhound', 'assets/images/legends/bloodhound.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Gibraltar', 'assets/images/legends/gibraltar.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Lifeline', 'assets/images/legends/lifeline.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Pathfinder', 'assets/images/legends/pathfinder.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Wraith', 'assets/images/legends/wraith.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Bangalore', 'assets/images/legends/bangalore.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Caustic', 'assets/images/legends/caustic.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Mirage', 'assets/images/legends/mirage.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Octane', 'assets/images/legends/octane.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Wattson', 'assets/images/legends/wattson.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Crypto', 'assets/images/legends/crypto.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Revenant', 'assets/images/legends/revenant.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Loba', 'assets/images/legends/loba.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Rampart', 'assets/images/legends/rampart.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Horizon', 'assets/images/legends/horizon.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Fuse', 'assets/images/legends/fuse.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Valkyrie', 'assets/images/legends/valkyrie.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Seer', 'assets/images/legends/seer.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Ash', 'assets/images/legends/ash.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Mad Maggie', 'assets/images/legends/mad_maggie.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Newcastle', 'assets/images/legends/newcastle.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Vantage', 'assets/images/legends/vantage.png' );
INSERT INTO legend(id, name, img_url) VALUES(default, 'Catalyst', 'assets/images/legends/catalyst.png');
INSERT INTO legend(id, name, img_url) VALUES(default, 'Ballistic', 'assets/images/legends/ballistic.png' );

--Weapons

INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Havoc', 'Assault Rifle', 'Energy', 'Short-Mid', false, 'assets/images/weapons/HAVOC_Rifle.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Flatline', 'Assault Rifle', 'Heavy', 'Mid', false, 'assets/images/weapons/VK-47_Flatline.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Hemlok', 'Assault Rifle', 'Heavy', 'Mid-Long', false, 'assets/images/weapons/Hemlok_Burst_AR.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'R-301', 'Sub-machine Gun', 'Light', 'Mid', false, 'assets/images/weapons/R-301_Carbine.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Alternator', 'Sub-machine Gun', 'Light', 'Short-Mid', false, 'assets/images/weapons/Alternator_SMG.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Prowler', 'Sub-machine Gun', 'Heavy', 'Short', true, 'assets/images/weapons/Prowler_Burst_PDW.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'R-99', 'Sub-machine Gun', 'Light', 'Short', false, 'assets/images/weapons/R-99_SMG.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Volt', 'Sub-machine Gun', 'Energy', 'Short-Mid', false, 'assets/images/weapons/Volt_SMG.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'CAR', 'Sub-machine Gun', 'Light/Heavy', 'Short', false, 'assets/images/weapons/C.A.R._SMG.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Devotion', 'Light Machine Gun', 'Energy', 'Short-Mid', false, 'assets/images/weapons/Devotion_LMG.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'L-Star', 'Light Machine Gun', 'Energy', 'Short', true, 'assets/images/weapons/L-STAR_EMG.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Spitfire', 'Light Machine Gun', 'Light', 'Short-Mid', false, 'assets/images/weapons/M600_Spitfire.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Rampage', 'Light Machine Gun', 'Heavy', 'Mid-Long', false, 'assets/images/weapons/Rampage_LMG.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'G7 Scout', 'Marksman Rifle', 'Light', 'Mid-Long', false, 'assets/images/weapons/G7_Scout.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, '30-30 Repeater', 'Marksman Rifle', 'Heavy', 'Mid-Long', false, 'assets/images/weapons/30-30_Repeater.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Triple Take', 'Marksman Rifle', 'Energy', 'Mid-Long', false, 'assets/images/weapons/Triple_Take.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Bochek', 'Marksman Rifle', 'Arrows', 'Mid-Long', true, 'assets/images/weapons/Bochek_Compound_Bow.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Charge Rifle', 'Sniper Rifle', 'Sniper', 'Long', false, 'assets/images/weapons/Charge_Rifle.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Sentinel', 'Sniper Rifle', 'Sniper', 'Long', false, 'assets/images/weapons/Sentinel.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Longbow', 'Sniper Rifle', 'Sniper', 'Mid-Long', false, 'assets/images/weapons/Longbow_DMR.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Kraber', 'Sniper Rifle', 'Sniper', 'Long', true, 'assets/images/weapons/Kraber_.50-Cal_Sniper.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Peacekeeper', 'Shotgun', 'Shotgun', 'Short', false, 'assets/images/weapons/Peacekeeper.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Eva-8', 'Shotgun', 'Shotgun', 'Short', false, 'assets/images/weapons/EVA-8_Auto.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Mozambique', 'Shotgun', 'Shotgun', 'Short', false, 'assets/images/weapons/Mozambique_Shotgun.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Mastiff', 'Shotgun', 'Shotgun', 'Short', false, 'assets/images/weapons/Mastiff_Shotgun.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'P2020', 'Pistol', 'Light', 'Short', false, 'assets/images/weapons/P2020.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'RE-45', 'Pistol', 'Light', 'Short', false, 'assets/images/weapons/RE-45_Auto.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Wingman', 'Pistol', 'Sniper', 'Short-Mid', false, 'assets/images/weapons/Wingman.webp');
INSERT INTO weapon(id, name, category, ammo_type, effective_range, is_drop_weapon, img_url) VALUES(default, 'Nemesis', 'Assault Rifle', 'Energy', 'Mid', false, 'assets/images/weapons/Nemesis_Burst_AR.webp');

--Apex Maps

INSERT INTO apex_map(id, name) VALUES(default, 'Miscellaneous');
INSERT INTO apex_map(id, name) VALUES(default, 'Kings Canyon');
INSERT INTO apex_map(id, name) VALUES(default, 'Stormpoint');
INSERT INTO apex_map(id, name) VALUES(default, 'Worlds Edge');
INSERT INTO apex_map(id, name) VALUES(default, 'Broken Moon');
INSERT INTO apex_map(id, name) VALUES(default, 'Olympus');

--Drop Locations

--Miscellaneous
INSERT INTO drop_location(id, map_id, name) VALUES(default, 1, 'Blue Zone');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 1, 'Straight Down');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 1, 'Last To Leave');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 1, 'Four Corners');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 1, 'Predator Snipe');
--Kings Canyon
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Crash Site');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Artillery');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Basin');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'The Rig');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Spotted Lake');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Containment');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Capacitor');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Runoff');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'The Pit');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Bunker');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'The Cage');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Labs');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Swamps');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Airbase');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Gauntlet');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Relic');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Market');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Hydro Dam');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Repulsor');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Caustic Treatment');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Map Room');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 2, 'Supply Ship');
--Stormpoint
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'North Pad');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'The Mill');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Highpoint');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Lightning Rod');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Downed Beast');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Checkpoint');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Cascade Falls');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Command Center');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Thunder Watch');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'The Wall');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Prowler Den');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Launch Pad');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Cenote Cave');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Barometer');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Antenna');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Ship Fall');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Gale Station');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Fish Farms');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 3, 'Nearest IMC Armory');
--Worlds Edge
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Trails');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Skyhook');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Survey Camp');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Climatizer');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Lava Fissure');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Landslide');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Countdown');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Fragment');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Monument');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'The Epicenter');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Overlook');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Staging');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Harvester');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'The Geyser');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Thermal Station');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'The Tree');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Lava Siphon');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Launch Site');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Lava City');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'The Dome');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Stacks');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'Geyser Vault');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 4, 'East of Fragment');
--Broken Moon
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'Alpha Base');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'Backup Atmo');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'The Core');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'Breaker Wharf');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'Dry Gulf');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'Stasis Array');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'Eternal Gardens');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'Production Yard');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'N. Promenade');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'S. Promenade');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'The Divide');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'The Foundry');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'Cultivation');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'Terraformer');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'Atmostation');
INSERT INTO drop_location(id, map_id, name) VALUES(default, 5, 'Bionomics');
--Olympus
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Estates');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Hammond Labs');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Solar Array');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Bonsai Plaza');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Orbital Cannon');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Docks');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Carrier');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Fight Night');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Power Grid');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Rift');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Turbine');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Energy Depot');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Gardens');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Clinic');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Oasis');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Grow Towers');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Elysium');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Hydroponics');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Phase Driver');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Icarus');
INSERT INTO drop_location(id, map_id, name) VALUES (default, 6, 'Terminal');